# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Punchcard-Swift-App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Punchcard-Swift-App
  pod 'ReSwift'
  pod 'Alamofire', '~> 4.3'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'Dwifft'
  pod 'MCSwipeTableViewCell', '~> 2.1.4'
  pod 'SwiftyUserDefaults'
end
